"""initial migrations

Revision ID: 423893433d57
Revises: 
Create Date: 2024-11-07 20:03:45.344351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423893433d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=100), nullable=False),
    sa.Column('color_scheme', sa.String(length=50), nullable=False),
    sa.Column('logo_picture', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    # ### end Alembic commands ###
